### PR TITLE
You should add more lasagna for our brains sanity

### PR DESCRIPTION
**Pull request by Dustley**

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
Is this glombus

**Comment by Dustley** [comment]
mhm!
Its so glombus plunger analog control stick

**Comment by RedstoneWizard08** [comment]
Real talk, I'm a little concerned about adding JAR files as there is a risk of potential malware - can you provide a source?

**Comment by Dustley** [comment]
didnt think about that- https://modrinth.com/mod/garfield thats the source

**Pull request merged**
